name: Build & Publish RPM repo

on:
  push:
    branches: [main]
    paths:
      - 'SPECS/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        dnf install -y rpmdevtools rpm-build createrepo_c dnf-plugins-core

    - name: Prepare RPM build tree
      run: rpmdev-setuptree

    - name: Download sources for specs
      run: |
        find SPECS -name '*.spec' | while read spec; do
          echo "Downloading sources for $spec"
          spectool -g -C ~/rpmbuild/SOURCES "$spec"
        done

    - name: Install build dependencies
      run: |
        find SPECS -name '*.spec' | while read spec; do
          echo "Installing build dependencies for $spec"
          dnf -y builddep "$spec" || true
        done

    - name: Build RPM packages
      run: |
        find SPECS -name '*.spec' | while read spec; do
          echo "Building $spec"
          cp "$spec" ~/rpmbuild/SPECS/
          rpmbuild -ba ~/rpmbuild/SPECS/$(basename "$spec") || true
        done

    - name: Collect RPMs
      run: |
        mkdir -p repo
        cp ~/rpmbuild/RPMS/**/*.rpm repo/ || true

    - name: Generate repository metadata
      run: createrepo_c repo/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages
