name: Build & Publish RPM to COPR

on:
  push:
    branches: [main]
    paths:
      - 'SPECS/**'
      - 'SOURCES/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools and copr-cli
      run: |
        dnf install -y rpmdevtools rpm-build spectool dnf-plugins-core \
                       git copr-cli python3-pip
        pip3 install --upgrade copr-cli

    - name: Configure copr-cli
      run: |
        mkdir -p ~/.config
        cat << EOF > ~/.config/copr
        [copr-cli]
        login = ${{ secrets.COPR_LOGIN }}
        username = ${{ secrets.COPR_USERNAME }}
        token = ${{ secrets.COPR_TOKEN }}
        copr_url = https://copr.fedorainfracloud.org
        EOF

    - name: Prepare RPM build tree
      run: rpmdev-setuptree

    - name: Copy source files
      run: |
        find SOURCES -type f -exec cp {} ~/rpmbuild/SOURCES/ \;
        find SPECS -name '*.spec' -exec cp {} ~/rpmbuild/SPECS/ \;

    - name: Download sources for specs
      run: |
        find ~/rpmbuild/SPECS -name '*.spec' | while read spec; do
          echo "Downloading sources for $spec"
          spectool -g -C ~/rpmbuild/SOURCES "$spec"
        done

    - name: Build SRPM and send to COPR
      run: |
        for spec in ~/rpmbuild/SPECS/*.spec; do
          echo "Building SRPM for $spec"
          rpmbuild -bs "$spec"
        done

        for srpm in ~/rpmbuild/SRPMS/*.src.rpm; do
          echo "Sending $srpm to COPR"
          copr-cli build krolmiki2011/CritOS "$srpm"
        done
